### PR TITLE
Adding Confluent Cloud sample app

### PR DESCRIPTION
**Pull request by matt-mangia**

### CODE REVIEW

**Review by fireinhole — APPROVED** [review]
LGTM

**Review by fireinhole — APPROVED** [review]
LGTM

**Review by fireinhole — APPROVED** [review]
LGTM

**Review by fireinhole — APPROVED** [review]

**Comment by matt-mangia** [comment]
@pascalconfluent @rkolesnev @eddyv --- mind taking a look if you have a chance at this PR / repo to see if you have any suggestions or feedback before I merge it in? Thanks!

**Pull request merged**
